apiVersion: "istio.openshift.com/v1alpha1"
kind: "Installation"
metadata:
  name: "istio-installation"
spec:
  deployment_type: origin
  istio:
    authentication: true
    community: false
    prefix: maistra/
    version: 0.5.0
  jaeger:
    prefix: jaegertracing/
    version: 1.8
    elasticsearch_memory: 1Gi
  kiali:
    username: kiali
    password: kiali
    prefix: kiali/
    version: v0.12
  launcher:
    openshift:
      user: developer
      password: developer
    github:
      username: username
      token: token
    catalog:
      filter: booster.mission.metadata.istio
      branch: v71
      repo: https://github.com/fabric8-launcher/launcher-booster-catalog.git